import { BaseTrack } from './BaseTrack'

export interface VideoTrack extends BaseTrack {
    '@type': 'Video';
    Format?: string;
    Format_Profile?: string;
    Format_Level?: string;
    Format_Tier?: string;
    HDR_Format?: string;
    HDR_Format_Version?: string;
    HDR_Format_Profile?: string;
    HDR_Format_Level?: string;
    HDR_Format_Settings?: string;
    HDR_Format_Compression?: string;
    HDR_Format_Compatibility?: string;
    CodecID: string;
    Duration: number;
    BitRate: number;
    Width: number;
    Height: number;
    Sampled_Width: number;
    Sampled_Height: number;
    PixelAspectRatio: number
    DisplayAspectRatio: number
    FrameRate_Mode: string;
    FrameRate: number;
    FrameRate_Num: number;
    FrameRate_Den: number;
    FrameCount: number;
    ColorSpace: string;
    ChromaSubsampling: string;
    ChromaSubsampling_Position: string;
    BitDepth: number;
    Delay: number;
    Delay_Source: string;
    StreamSize: number;
    Language: string;
    Default: string;
    Forced: string;
    colour_description_present: string;
    colour_description_present_Source: string;
    colour_range: string;
    colour_range_Source: string;
    colour_primaries: string;
    colour_primaries_Source: string;
    transfer_characteristics: string;
    transfer_characteristics_Source: string;
    matrix_coefficients: string;
    matrix_coefficients_Source: string;
    MasteringDisplay_ColorPrimaries: string;
    MasteringDisplay_ColorPrimaries_Source: string;
    MasteringDisplay_Luminance: string;
    MasteringDisplay_Luminance_Source: string;
    MaxCLL: string;
    MaxCLL_Source: string;
    MaxFALL: string;
    MaxFALL_Source: string;
    LOCAL_INDEX?: number;
}